deployment-steps: &steps
      - checkout
      - setup_remote_docker
      - restore_cache:
            key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
            name: "What branch am I on?"
            command: echo ${CIRCLE_BRANCH}
      - run:
            command: |
                npm install
                sudo apt-get update
      - save_cache:
            key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
            paths:
                  - "node_modules"
      - run:
            name: show directorry
            command: ls -a
      - run:
              name: build app
              command: xvfb-run -a npm run build:ssr
      - run:
            name: BUILD DOCKER
            command: |
                docker build -t sloge/goove:$CIRCLE_BUILD_NUM .
                echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
                docker push sloge/goove:$CIRCLE_BUILD_NUM


jobs:
    build-qa:
        working_directory: ~/goove
        environment:
            ENV: 'qa'
        docker:
            - image: circleci/node:12-browsers
        steps: *steps


    build-prod:
        working_directory: ~/goove
        environment:
            ENV: 'prod'
        docker:
            - image: circleci/node:12-browsers
        steps: *steps


workflows:
    version: 2
    build:
        jobs:
            - build-qa:
                filters:
                    branches:
                        ignore: master
            - build-prod:
                filters:
                    branches:
                        only: master
