version: 2
jobs:
  build:
    working_directory: ~/goove
    branches:
        only:
            - master
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: |
            npm install;
            sudo apt-get update;
            sudo apt-get install lftp;
                echo "ENV: $ENV Deployment dir: $DEPLOY_DIR";
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: show directorry
          command: ls -a
      - run:
          name: build app
          command: xvfb-run -a npm run build
      - run:
          name: push to ftp
          command: |
              lftp ftp://${username}:${password}@${hostname}/${DEPLOY_DIR}/ -e "mirror -c -R -v --Remove-source-files --Remove-source-dirs dist/goove/.; bye";
              lftp ftp://${username}:${password}@${hostname}/${DEPLOY_DIR}/ -e "put .deployment/${ENV}/.htaccess; bye";


