deployment-steps: &steps
  - checkout
  - setup_remote_docker
  - restore_cache:
      key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
  - run:
      command: |
        npm install
        sudo apt-get update
  - save_cache:
      key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      paths:
        - "node_modules"
  - run:
      name: show directorry
      command: ls -a
  - run:
      name: build app
      command: |
        xvfb-run -a npm run build

  - run:
      name: BUILD DOCKER
      command: |
        docker build -t sloge/export-latest:$CIRCLE_BUILD_NUM .
        docker tag sloge/export-latest:$CIRCLE_BUILD_NUM  sloge/export-latest:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
        docker push sloge/export-latest

  - run:
      name: DEPLOY DOCKER
      command: |
        ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "docker-compose up -d --force-recreate"
jobs:
  build-prod:
    working_directory: ~/export-latest
    environment:
      ENV: 'prod'
    docker:
      - image: circleci/node:12-browsers
    steps: *steps


workflows:
  version: 2
  build:
    jobs:
      - build-prod:
          filters:
            branches:
              only: main
