deployment-steps: &steps
      - checkout
      - restore_cache:
            key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
            name: "What branch am I on?"
            command: echo ${CIRCLE_BRANCH}
      - run:
            command: |
                echo "ENV: $ENV Deployment dir: $DEPLOY_DIR"
                npm install
                sudo apt-get update
                sudo apt-get install lftp
      - save_cache:
            key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
            paths:
                  - "node_modules"
      - run:
            name: show directorry
            command: ls -a
      - run:
              name: build app
              command: xvfb-run -a npm run build
      - run:
            name: Push to FTP QA
            command: |
                echo "deploying QA, to: ${DEPLOY_DIRECTORY}"
                lftp ftp://${username}:${password}@${hostname}/${DEPLOY_DIRECTORY} -e "mirror -c -R -v --Remove-source-files --Remove-source-dirs dist/goove/.; bye";
                lftp ftp://${username}:${password}@${hostname}/${DEPLOY_DIRECTORY} -e "put .deployment/${ENV}/.htaccess; bye";



jobs:
    build-qa:
        working_directory: ~/goove
        environment:
            ENV: 'qa'
            DEPLOY_DIRECTORY: 'goove/'
        docker:
            - image: circleci/node:12-browsers
        steps: *steps


    build-prod:
        working_directory: ~/goove
        environment:
            ENV: 'prod'
            DEPLOY_DIRECTORY: 'locations/app/'
        docker:
            - image: circleci/node:12-browsers
        steps: *steps


workflows:
    version: 2
    build:
        jobs:
            - build-qa:
                filters:
                    branches:
                        ignore: master
            - build-prod:
                filters:
                    branches:
                        only: master
