deployment-steps: &steps
      - checkout
      - attach_workspace:
            at: /tmp/workspace

      - setup_remote_docker
      - restore_cache:
            key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
            name: "What branch am I on?"
            command: echo ${CIRCLE_BRANCH}
      - run:
            command: |
                npm install
                sudo apt-get update
      - save_cache:
            key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
            paths:
                  - "node_modules"
      - run:
            name: show directorry
            command: ls -a
      - run:
              name: build app
              command: |
                  xvfb-run -a npm run increase:version
                  xvfb-run -a npm run build:ssr
      -   run:
              name: copy important files
              command: |
                  cp dist/goove/browser/assets/google05fe7ee3897b21a6.html dist/goove/browser
                  cp /tmp/workspace/sitemap.xml dist/goove/browser

      - run:
            name: BUILD DOCKER
            command: |
                docker build -t sloge/goove:$CIRCLE_BUILD_NUM .
                echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
                docker push sloge/goove:$CIRCLE_BUILD_NUM


jobs:
    build-sitemap:
        working_directory: ~/goove
        docker:
            -   image: circleci/python:3.7.8
        steps:
            - checkout
            - run:
                  name: building sitemap
                  command: |
                      mkdir -p /tmp/workspace
                      pip install requests
                      python scripts/generate.py
                      cp sitemap.xml /tmp/workspace/
                      ls /tmp/workspace/

            - persist_to_workspace:
                  root: /tmp/workspace
                  paths:
                      - sitemap.xml
    build-qa:
        working_directory: ~/goove
        environment:
            ENV: 'qa'
        docker:
            - image: circleci/node:12-browsers
        steps: *steps


    build-prod:
        working_directory: ~/goove
        environment:
            ENV: 'prod'
        docker:
            - image: circleci/node:12-browsers
        steps: *steps


workflows:
    version: 2
    build:
        jobs:
            - build-sitemap
            - build-qa:
                requires:
                    - build-sitemap
                filters:
                    branches:
                        ignore: master
            - build-prod:
                requires:
                    - build-sitemap
                filters:
                    branches:
                        only: master
